const employeesColumn = [
    {
        "id": 1,
        "name": "Jeffery Lalor",
        "firstName": "Jeffery",
        "lastName": "Lalor",
        "cnic": "35201-1234567-8",
        "designation": "Team Leader",
        "email": "jefferylalor@example.com",
        "contact": "0301-1234567",
        "dob": "1985-05-15",
        "currentAddress": "123 Elm Street, Springfield",
        "joiningDate": "2013-01-01",
        "endDate": null,
        "duration": "11 years",
        "contract": true,
        "guardianName": "John Lalor",
        "guardianContact": "0321-7654321",
        "relation": "Father",
        "permanentAddress": "456 Oak Street, Springfield",
        "bankName": "ABC Bank",
        "accountNumber": "1234567890123456",
        "accountTitle": "Jeffery Lalor",
        "status": false,
        "createdBy": "user1",
        "salary": "20000"
    },
    {
        "id": 2,
        "name": "John Doe",
        "firstName": "John",
        "lastName": "Doe",
        "cnic": "35201-7654321-0",
        "designation": "Web Designer",
        "email": "johndoe@example.com",
        "contact": "0302-9876543",
        "dob": "1990-09-20",
        "currentAddress": "789 Maple Street, Springfield",
        "joiningDate": "2015-06-01",
        "endDate": "2016-06-01",
        "duration": "8 years",
        "contract": false,
        "guardianName": "David Doe",
        "guardianContact": "0333-2222222",
        "relation": "Father",
        "permanentAddress": "321 Pine Street, Springfield",
        "bankName": "XYZ Bank",
        "accountNumber": "0987654321098765",
        "accountTitle": "John Doe",
        "status": true,
        "createdBy": "user2",
        "salary": "50000"
    },
    {
        "id": 3,
        "name": "Alice Smith",
        "firstName": "Alice",
        "lastName": "Smith",
        "cnic": "35202-1122334-5",
        "designation": "Software Engineer",
        "email": "alicesmith@example.com",
        "contact": "0303-1122334",
        "dob": "1992-03-10",
        "currentAddress": "101 Birch Street, Springfield",
        "joiningDate": "2017-09-15",
        "endDate": null,
        "duration": "6 years",
        "contract": true,
        "guardianName": "Sarah Smith",
        "guardianContact": "0344-4455667",
        "relation": "Mother",
        "permanentAddress": "202 Cedar Street, Springfield",
        "bankName": "DEF Bank",
        "accountNumber": "2345678901234567",
        "accountTitle": "Alice Smith",
        "status": true,
        "createdBy": "user3",
        "salary": "60000"
    },
    {
        "id": 4,
        "name": "Michael Brown",
        "firstName": "Michael",
        "lastName": "Brown",
        "cnic": "35203-5566778-9",
        "designation": "Data Analyst",
        "email": "michaelbrown@example.com",
        "contact": "0304-4455667",
        "dob": "1988-11-25",
        "currentAddress": "303 Maple Street, Springfield",
        "joiningDate": "2018-01-01",
        "endDate": null,
        "duration": "5 years",
        "contract": true,
        "guardianName": "Henry Brown",
        "guardianContact": "0355-6677889",
        "relation": "Uncle",
        "permanentAddress": "404 Oak Street, Springfield",
        "bankName": "GHI Bank",
        "accountNumber": "3456789012345678",
        "accountTitle": "Michael Brown",
        "status": false,
        "createdBy": "user4",
        "salary": "45000"
    },
    {
        "id": 5,
        "name": "Emma Wilson",
        "firstName": "Emma",
        "lastName": "Wilson",
        "cnic": "35204-9988776-3",
        "designation": "HR Manager",
        "email": "emmawilson@example.com",
        "contact": "0305-7788990",
        "dob": "1987-02-15",
        "currentAddress": "505 Pine Street, Springfield",
        "joiningDate": "2012-05-01",
        "endDate": null,
        "duration": "12 years",
        "contract": true,
        "guardianName": "Laura Wilson",
        "guardianContact": "0366-8899001",
        "relation": "Mother",
        "permanentAddress": "606 Elm Street, Springfield",
        "bankName": "JKL Bank",
        "accountNumber": "4567890123456789",
        "accountTitle": "Emma Wilson",
        "status": true,
        "createdBy": "user5",
        "salary": "70000"
    },
    {
        "id": 6,
        "name": "David Johnson",
        "firstName": "David",
        "lastName": "Johnson",
        "cnic": "35205-5544332-7",
        "designation": "Marketing Executive",
        "email": "davidjohnson@example.com",
        "contact": "0306-3344556",
        "dob": "1991-07-21",
        "currentAddress": "707 Cedar Street, Springfield",
        "joiningDate": "2016-03-10",
        "endDate": null,
        "duration": "7 years",
        "contract": false,
        "guardianName": "Andrew Johnson",
        "guardianContact": "0377-4455667",
        "relation": "Brother",
        "permanentAddress": "808 Birch Street, Springfield",
        "bankName": "MNO Bank",
        "accountNumber": "5678901234567890",
        "accountTitle": "David Johnson",
        "status": true,
        "createdBy": "user6",
        "salary": "55000"
    },
    {
        "id": 7,
        "name": "Sophia Martinez",
        "firstName": "Sophia",
        "lastName": "Martinez",
        "cnic": "35206-6677889-0",
        "designation": "UI/UX Designer",
        "email": "sophiamartinez@example.com",
        "contact": "0307-5566778",
        "dob": "1993-08-14",
        "currentAddress": "909 Maple Street, Springfield",
        "joiningDate": "2019-10-01",
        "endDate": null,
        "duration": "4 years",
        "contract": true,
        "guardianName": "Carlos Martinez",
        "guardianContact": "0388-6677889",
        "relation": "Father",
        "permanentAddress": "1010 Oak Street, Springfield",
        "bankName": "PQR Bank",
        "accountNumber": "6789012345678901",
        "accountTitle": "Sophia Martinez",
        "status": false,
        "createdBy": "user7",
        "salary": "62000"
    },
    {
        "id": 8,
        "name": "Daniel Lee",
        "firstName": "Daniel",
        "lastName": "Lee",
        "cnic": "35207-4455667-1",
        "designation": "Project Manager",
        "email": "daniellee@example.com",
        "contact": "0308-4455667",
        "dob": "1989-01-30",
        "currentAddress": "1111 Birch Street, Springfield",
        "joiningDate": "2014-08-01",
        "endDate": null,
        "duration": "9 years",
        "contract": true,
        "guardianName": "Michael Lee",
        "guardianContact": "0399-7788990",
        "relation": "Father",
        "permanentAddress": "1212 Elm Street, Springfield",
        "bankName": "STU Bank",
        "accountNumber": "7890123456789012",
        "accountTitle": "Daniel Lee",
        "status": true,
        "createdBy": "user8",
        "salary": "80000"
    },
    {
        "id": 9,
        "name": "Olivia White",
        "firstName": "Olivia",
        "lastName": "White",
        "cnic": "35208-2233445-6",
        "designation": "Business Analyst",
        "email": "oliviawhite@example.com",
        "contact": "0309-2233445",
        "dob": "1994-12-12",
        "currentAddress": "1313 Cedar Street, Springfield",
       "joiningDate": "2014-08-01",
        "endDate": null,
        "duration": "9 years",
        "contract": true,
        "guardianName": "Michael Lee",
        "guardianContact": "0399-7788990",
        "relation": "Father",
        "permanentAddress": "1212 Elm Street, Springfield",
        "bankName": "STU Bank",
        "accountNumber": "7890123456789012",
        "accountTitle": "Daniel Lee",
        "status": true,
        "createdBy": "user8",
        "salary": "80000"}
];

export { employeesColumn };
