const employeesColumn = [
    {
        "id":1,
        "name": "Jeffery Lalor",
        "cnic": "35201-1234567-8",
        "designation": "Team Leader",
        "email": "jefferylalor@example.com",
        "contact": "0301-1234567",
        "dob": "1985-05-15",
        "currentAddress": "123 Elm Street, Springfield",
        "joiningDate": "2013-01-01",
        "endDate": null,
        "duration": "11 years",
        "contract": "false",
        "guardianName": "John Lalor",
        "guardianContact": "0321-7654321",
        "relation": "Father",
        "permanentAddress": "456 Oak Street, Springfield",
        "bankName": "ABC Bank",
        "accountNumber": "1234567890123456",
        "accountTitle": "Jeffery Lalor",
        "status": "Active",
        "createdBy":"user1",
    },
    {
        "id":2,
        "name": "John Doe",
        "cnic": "35201-7654321-0",
        "designation": "Web Designer",
        "email": "johndoe@example.com",
        "contact": "0302-9876543",
        "dob": "1990-09-20",
        "currentAddress": "789 Maple Street, Springfield",
        "joiningDate": "2015-06-01",
        "endDate": null,
        "duration": "8 years",
        "contract": "true",
        "guardianName": "David Doe",
        "guardianContact": "0333-2222222",
        "relation": "Father",
        "permanentAddress": "321 Pine Street, Springfield",
        "bankName": "XYZ Bank",
        "accountNumber": "0987654321098765",
        "accountTitle": "John Doe",
        "status": "Active",
        "createdBy":"user2",

    }
];

export { employeesColumn };
